spring.datasource.url=jdbc:postgresql://localhost:5432/software_architecture_playground
spring.datasource.username=postgres
spring.datasource.password=Satya@2006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true